
name: MainJob
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github\workflows\**.*'
  schedule:
    - cron:  '00 0 * * *'

jobs:
  updater:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.9]



    steps:
    - uses: actions/checkout@v3

    - name: Setting Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Installing Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install mkdocs
        pip install mkdocs-material
        pip install Pygments
        sudo apt install cloc

    - name: Pre-Configuring Git
      run: |
        git config user.name github-workflow
        git config user.email github-actions@github.com
        git config --global http.postBuffer 1048576000

    - name: Upgrading Packages
      continue-on-error: true
      # Thanks To https://stackoverflow.com/questions/2720014/how-to-upgrade-all-python-packages-with-pip
      run: |
        pip --disable-pip-version-check list --outdated --format=json | python -c "import json, sys; print('\n'.join([x['name'] for x in json.load(sys.stdin)]))"

    - name: Building Documentation
      continue-on-error: true
      run: |
        mkdocs build --config-file Documentation/mkdocs.yml

    - name: Running Main Python Script
      continue-on-error: true
      run: |
        python .github/workflows/Main.py

    - name: Cleaning PYCACHE
      continue-on-error: true
      run: |
        cd .github/workflows/
        sudo find . | grep -E "(/__pycache__$|\.pyc$|\.pyo$)" | xargs rm -rf
        cd ../..

    - name: Deploying Documentation
      continue-on-error: true
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/site
        publish_branch: documentation

    - name: Pushing Changes
      continue-on-error: true
      run: |
        git add .
        git commit -m "<Updated File>"
        git push

        
